# Generated by Django 4.0.4 on 2022-05-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_tag_name'),
        ('orders', '0004_order_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='products.product'),
        ),
    ]
