# Generated by Django 4.0.4 on 2022-05-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('shirts', 'shirts'), ('pants', 'pants'), ('sweaters', 'sweaters'), ('chalk_bags', 'chalk bags'), ('chalk_buckets', 'chalk buckets'), ('brushes', 'brushes'), ('bottles', 'bottles')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Climbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', related_query_name='%(class)ss', to='products.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L'), ('xlarge', 'XL')], max_length=50)),
                ('gender', models.CharField(choices=[('mens', 'mens'), ('womens', 'womens'), ('other', 'other')], max_length=50)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', related_query_name='%(class)ss', to='products.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
