# Generated by Django 4.0.4 on 2022-05-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('shirts', 'shirts'), ('pants', 'pants'), ('sweaters', 'sweaters'), ('chalk bags', 'chalk bags'), ('chalk buckets', 'chalk buckets'), ('brushes', 'brushes'), ('bottles', 'bottles')], max_length=100),
        ),
    ]
